apiVersion: v1
kind: Namespace
metadata:
  name: stackrox
---
apiVersion: v1
kind: Namespace
metadata:
  name: rhacs-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhacs-operator-group
  namespace: rhacs-operator
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhacs-operator
  namespace: rhacs-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: rhacs-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: v1
data:
  admission-control-cert.pem: '{{hub fromSecret "acs-install-policies" "admission-control-tls" "admission-control-cert.pem" hub}}'
  admission-control-key.pem: '{{hub fromSecret "acs-install-policies" "admission-control-tls" "admission-control-key.pem" hub}}'
  ca.pem: '{{hub fromSecret "acs-install-policies" "admission-control-tls" "ca.pem" hub}}'
kind: Secret
metadata:
  name: admission-control-tls
  namespace: stackrox
type: Opaque
---
apiVersion: v1
data:
  collector-cert.pem: '{{hub fromSecret "acs-install-policies" "collector-tls" "collector-cert.pem" hub}}'
  collector-key.pem: '{{hub fromSecret "acs-install-policies" "collector-tls" "collector-key.pem" hub}}'
  ca.pem: '{{hub fromSecret "acs-install-policies" "collector-tls" "ca.pem" hub}}'
kind: Secret
metadata:
  name: collector-tls
  namespace: stackrox
type: Opaque
---
apiVersion: v1
data:
  sensor-cert.pem: '{{hub fromSecret "acs-install-policies" "sensor-tls" "sensor-cert.pem" hub}}'
  sensor-key.pem: '{{hub fromSecret "acs-install-policies" "sensor-tls" "sensor-key.pem" hub}}'
  ca.pem: '{{hub fromSecret "acs-install-policies" "sensor-tls" "ca.pem" hub}}'
  acs-host: '{{hub fromSecret "acs-install-policies" "sensor-tls" "acs-host" hub}}'
kind: Secret
metadata:
  name: sensor-tls
  namespace: stackrox
type: Opaque
---
apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  namespace: stackrox
  name: stackrox-secured-cluster-services
spec:
  clusterName: |
    {{ fromClusterClaim "name" }}
  auditLogs:
    collection: Auto
  centralEndpoint: |
    {{ fromSecret "stackrox" "sensor-tls" "acs-host" | base64dec }}
  admissionControl:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/infra: ""
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        value: reserved
      - effect: NoExecute
        key: node-role.kubernetes.io/infra
        value: reserved
    listenOnCreates: false
    listenOnEvents: true
    listenOnUpdates: false
  perNode:
    collector:
      collection: EBPF
      imageFlavor: Regular
    taintToleration: TolerateTaints
  scanner:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/infra: ""
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        value: reserved
      - effect: NoExecute
        key: node-role.kubernetes.io/infra
        value: reserved
  sensor:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/infra: ""
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        value: reserved
      - effect: NoExecute
        key: node-role.kubernetes.io/infra
        value: reserved